### ISSUE TITLE
Remodel the current sequence part in the ontology

### ISSUE THREAD

**Issue by gopalkoduri** [gopalkoduri/ontologies#1]
From the feedback I got in the summer school, simplicity seems to be the first priority. And it is also said that the rdfs vocabulary or the ordered-list ontology might suffice for representing sequence, given that SPARQL 1.1 has a lot of added stuff that we could use to make inferences (using SPIN rules).

**Comment by sertansenturk** [comment]
If you are only dealing with time-interval sequences, you can use **time:intervalMeets**: http://www.w3.org/TR/owl-time/

**Comment by gopalkoduri** [comment]
After comparing OWLList (Nick Drummond et al), SEQ (Wissman et al) and Ordered List Ontology/OLO (Abdallah and Ferris), we are going with OLO (with modifications in future as necessary) as it provides a simple enough way to represent sequences. In addition, it is not possible to count in OWLList and SEQ, making them unfit for some of the raaga classification tasks in ontology (audava, shadava, sampoorna).

**Comment by sertansenturk** [comment]
As a side note, when using OLO, Fact++ works better/faster than the default reasoner in Protege 4.
